### PR TITLE
cube: unbreak KHR_display with Clang

### LINKED ISSUE #686: vkcube (KHR_display) fails to build since v1.2.173 (-Werror, Clang, -DNDEBUG)
Regressed by 27c21248221f. Found [downstream](http://www.ipv6proxy.net/go.php?u=http://package23.nyi.freebsd.org/data/131i386-default-foo/2022-10-02_07h26m38s/logs/errors/vulkan-tools-1.3.230.log) because `-DCMAKE_BUILD_TYPE=Release` [adds `-DNDEBUG`](https://github.com/Kitware/CMake/blob/v3.24.0/Modules/Compiler/GNU.cmake#L59) thus makes `assert()` [expand to nothing](https://github.com/freebsd/freebsd-src/blob/releng/13.1/include/assert.h#L51).

```
$ cc --version
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
```

```c
$ cmake -DCMAKE_BUILD_TYPE=Release -DCUBE_WSI_SELECTION=DISPLAY -B /tmp/vulkan-tools_build
$ cmake --build /tmp/vulkan-tools_build
[...]
cube/cube.c:3122:14: error: variable 'result' set but not used [-Werror,-Wunused-but-set-variable]
    VkResult result;
             ^
1 error generated.
```

Note, GCC doesn't trip `-Werror` despite `BUILD_WERROR` enabled by default:
```c
cube/cube.c: In function 'find_display_gpu':
cube/cube.c:3122:14: warning: variable 'result' set but not used [-Wunused-but-set-variable]
 3122 |     VkResult result;
      |              ^~~~~~
```

### PR DESCRIPTION
**Pull request by jbeich**
Fixes #686

### CODE REVIEW

**Comment by jbeich** [comment]
Ugh, I did sign CLA years ago (for changes landed in Vulkan-Loader). GitHub probably revoked authorization (to my profile) from CLAassistant.

**Review by charles-lunarg — APPROVED** [review]

**Comment by charles-lunarg** [comment]
Yes I remember that PR, so I wont require that here.
