### PR TITLE
Fix cubepp implicit cast

### LINKED ISSUE #649: vkcubepp (KHR_display) fails to build since v1.3.213
Regressed by https://github.com/KhronosGroup/Vulkan-Headers/commit/33d4dd987fc8

```
$ cmake -DCUBE_WSI_SELECTION=DISPLAY -B /tmp/vulkan-tools_build
$ cmake --build /tmp/vulkan-tools_build
[...]
FAILED: cube/CMakeFiles/vkcubepp.dir/cube.cpp.o
/usr/bin/c++ -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_DISPLAY_KHR -I/tmp/vulkan-tools_build/cube -I/tmp/vulkan-tools/cube -I/tmp/vulkan-tools_build/cube/.. -isystem /usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Werror -std=c++11 -fno-rtti -fvisibility=hidden -MD -MT cube/CMakeFiles/vkcubepp.dir/cube.cpp.o -MF cube/CMakeFiles/vkcubepp.dir/cube.cpp.o.d -o cube/CMakeFiles/vkcubepp.dir/cube.cpp.o -c /tmp/vulkan-tools/cube/cube.cpp
cube/cube.cpp:2965:37: error: no viable conversion from 'typename ResultValueType<vk::DisplayPlaneCapabilitiesKHR>::type' (aka 'ResultValue<vk::DisplayPlaneCapabilitiesKHR>') to 'vk::DisplayPlaneCapabilitiesKHR'
    vk::DisplayPlaneCapabilitiesKHR planeCaps = gpu.getDisplayPlaneCapabilitiesKHR(display_mode_prop.displayMode, plane_found);
                                    ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:26060:26: note: candidate constructor not viable: no known conversion from 'typename ResultValueType<vk::DisplayPlaneCapabilitiesKHR>::type' (aka 'ResultValue<vk::DisplayPlaneCapabilitiesKHR>') to 'vk::DisplayPlaneAlphaFlagsKHR' (aka 'Flags<vk::DisplayPlaneAlphaFlagBitsKHR>') for 1st argument
    VULKAN_HPP_CONSTEXPR DisplayPlaneCapabilitiesKHR( VULKAN_HPP_NAMESPACE::DisplayPlaneAlphaFlagsKHR supportedAlpha_ = {},
                         ^
/usr/include/vulkan/vulkan_structs.hpp:26081:26: note: candidate constructor not viable: no known conversion from 'typename ResultValueType<vk::DisplayPlaneCapabilitiesKHR>::type' (aka 'ResultValue<vk::DisplayPlaneCapabilitiesKHR>') to 'const vk::DisplayPlaneCapabilitiesKHR &' for 1st argument
    VULKAN_HPP_CONSTEXPR DisplayPlaneCapabilitiesKHR( DisplayPlaneCapabilitiesKHR const & rhs ) VULKAN_HPP_NOEXCEPT = default;
                         ^
/usr/include/vulkan/vulkan_structs.hpp:26083:5: note: candidate constructor not viable: no known conversion from 'typename ResultValueType<vk::DisplayPlaneCapabilitiesKHR>::type' (aka 'ResultValue<vk::DisplayPlaneCapabilitiesKHR>') to 'const VkDisplayPlaneCapabilitiesKHR &' for 1st argument
    DisplayPlaneCapabilitiesKHR( VkDisplayPlaneCapabilitiesKHR const & rhs ) VULKAN_HPP_NOEXCEPT
    ^
/usr/include/vulkan/vulkan.hpp:5917:5: note: candidate function
    operator std::tuple<Result &, T &>() VULKAN_HPP_NOEXCEPT
    ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by mikes-lunarg**
Fix a compiler error with `-DCUBE_WSI_SELECTION=DISPLAY` and Vulkan-Headers v1.3.213

Add more WSI options in addition to the default XCB to the GitHub Actions linux job to catch these types of failures in the future.

Fixes #649

### CODE REVIEW

**Review by charles-lunarg — APPROVED** [review]

**Review by Tony-LunarG — APPROVED** [review]
LGTM and nice test additions
