### PR TITLE
vulkaninfo: build with 1.1.117 vulkan header

### LINKED ISSUE #230: vulkaninfo: fails to compile against vulkan-headers 1.1.117
Works with vulkan-headers 1.1.115, fails with 1.1.117:

```
[ 50%] Building C object vulkaninfo/CMakeFiles/vulkaninfo.dir/vulkaninfo.c.o
cd /var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/build/vulkaninfo && /usr/bin/x86_64-pc-linux-gnu-cc -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR  -march=native -O2 -pipe -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -fvisibility=hidden   -o CMakeFiles/vulkaninfo.dir/vulkaninfo.c.o   -c /var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c
make -j5
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c: In function 'AppGpuDumpProps':
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c:4515:48: error: 'VkPhysicalDeviceFloatControlsPropertiesKHR' {aka 'struct VkPhysicalDeviceFloatControlsPropertiesKHR'} has no member named 'separateDenormSettings'
                             float_control_props->separateDenormSettings);
                                                ^~
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c:4519:48: error: 'VkPhysicalDeviceFloatControlsPropertiesKHR' {aka 'struct VkPhysicalDeviceFloatControlsPropertiesKHR'} has no member named 'separateRoundingModeSettings'
                             float_control_props->separateRoundingModeSettings);
                                                ^~
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c:4584:102: error: 'VkPhysicalDeviceFloatControlsPropertiesKHR' {aka 'struct VkPhysicalDeviceFloatControlsPropertiesKHR'} has no member named 'separateDenormSettings'
                     printf("\tseparateDenormSettings       = %" PRIuLEAST32 "\n", float_control_props->separateDenormSettings);
                                                                                                      ^~
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c:4586:47: error: 'VkPhysicalDeviceFloatControlsPropertiesKHR' {aka 'struct VkPhysicalDeviceFloatControlsPropertiesKHR'} has no member named 'separateRoundingModeSettings'
                            float_control_props->separateRoundingModeSettings);
                                               ^~
```

### PR DESCRIPTION
**Pull request by dgkoch**
Fixes #230

### CODE REVIEW

**Comment by shannon-lunarg** [comment]
Hello! The Vulkan-Tools known-good and generated source files have not yet been updated because we are waiting for a code change concerning build dependencies to be merged to master. This has been in the works for about a week. We are currently performing internal testing on the required changes and the known-good will be updated shortly after they are merged. In the future, I will be creating an issue in this repo if known-good updates are delayed for a significant amount of time. I will comment here once the 117 known-good has been updated.

**Comment by dgkoch** [comment]
@shannon-lunarg I'm not sure the implications of all that. Does that mean you don't want/need this change, or it's blocked until those changes have landed?

**Comment by shannon-lunarg** [comment]
These changes to `vulkaninfo` look equivalent to those already incorporated in [the branch I'm using to update the known good](https://github.com/KhronosGroup/Vulkan-Tools/commit/7d8cf8c9d0d887c6e9058e078c2f67bd02b96606#diff-e1bf92b9c49977ed0508a1ad658ee9f6) but let me know if I've over looked something. I won't be able to make these changes until the above mentioned PR is approved and Vulkan-Loader is healthy again. I'm sorry the header update delay has caused duplication of work.

**Comment by dgkoch** [comment]
The changes do look equivalent.  I'll leave this here until the other change is merged, in case anyone needs this in the meantime. Feel free to close it if your version gets merged.

**Comment by shannon-lunarg** [comment]
The changes I was waiting on that I mentioned earlier have been merged to VT master and exposed a new problem with `vulkan.hpp`. An issue has been raised in the Vulkan-Hpp repo to address this new issue but will further delay updating this repo's known-good.

**Comment by charles-lunarg** [comment]
Closing this PR because 1.1.119 changes have been merged in.
