### ISSUE TITLE
vkcubepp (KHR_wayland_surface) fails to build since v1.3.209

### ISSUE THREAD

**Issue by jbeich** [KhronosGroup/Vulkan-Tools#635]
Regressed by 3bcefe5770cf
```c++
$ cmake -DCUBE_WSI_SELECTION=WAYLAND -B /tmp/vulkan-tools_build
$ cmake --build /tmp/vulkan-tools_build
[...]
cube/cube.cpp:489:9: error: no matching function for call to 'wl_pointer_add_listener'
        wl_pointer_add_listener(demo.pointer, &pointer_listener, demo);
        ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wayland-client-protocol.h:4671:1: note: candidate function not viable: no known conversion from 'Demo' to 'void *' for 3rd argument; take the address of the argument with &
wl_pointer_add_listener(struct wl_pointer *wl_pointer,
^
cube/cube.cpp:497:9: error: no matching function for call to 'wl_keyboard_add_listener'
        wl_keyboard_add_listener(demo.keyboard, &keyboard_listener, demo);
        ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wayland-client-protocol.h:4986:1: note: candidate function not viable: no known conversion from 'Demo' to 'void *' for 3rd argument; take the address of the argument with &
wl_keyboard_add_listener(struct wl_keyboard *wl_keyboard,
^
cube/cube.cpp:522:9: error: no matching function for call to 'wl_seat_add_listener'
        wl_seat_add_listener(demo.seat, &seat_listener, demo);
        ^~~~~~~~~~~~~~~~~~~~
/usr/include/wayland-client-protocol.h:4171:1: note: candidate function not viable: no known conversion from 'Demo' to 'void *' for 3rd argument; take the address of the argument with &
wl_seat_add_listener(struct wl_seat *wl_seat,
^
3 errors generated.
```
