### ISSUE TITLE
vulkaninfo: fails to compile against vulkan-headers 1.1.117

### ISSUE THREAD

**Issue by tgurr** [KhronosGroup/Vulkan-Tools#230]
Works with vulkan-headers 1.1.115, fails with 1.1.117:

```
[ 50%] Building C object vulkaninfo/CMakeFiles/vulkaninfo.dir/vulkaninfo.c.o
cd /var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/build/vulkaninfo && /usr/bin/x86_64-pc-linux-gnu-cc -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR  -march=native -O2 -pipe -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -fvisibility=hidden   -o CMakeFiles/vulkaninfo.dir/vulkaninfo.c.o   -c /var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c
make -j5
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c: In function 'AppGpuDumpProps':
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c:4515:48: error: 'VkPhysicalDeviceFloatControlsPropertiesKHR' {aka 'struct VkPhysicalDeviceFloatControlsPropertiesKHR'} has no member named 'separateDenormSettings'
                             float_control_props->separateDenormSettings);
                                                ^~
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c:4519:48: error: 'VkPhysicalDeviceFloatControlsPropertiesKHR' {aka 'struct VkPhysicalDeviceFloatControlsPropertiesKHR'} has no member named 'separateRoundingModeSettings'
                             float_control_props->separateRoundingModeSettings);
                                                ^~
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c:4584:102: error: 'VkPhysicalDeviceFloatControlsPropertiesKHR' {aka 'struct VkPhysicalDeviceFloatControlsPropertiesKHR'} has no member named 'separateDenormSettings'
                     printf("\tseparateDenormSettings       = %" PRIuLEAST32 "\n", float_control_props->separateDenormSettings);
                                                                                                      ^~
/var/tmp/paludis/build/sys-apps-vulkan-tools-1.1.114/work/Vulkan-Tools-1.1.114/vulkaninfo/vulkaninfo.c:4586:47: error: 'VkPhysicalDeviceFloatControlsPropertiesKHR' {aka 'struct VkPhysicalDeviceFloatControlsPropertiesKHR'} has no member named 'separateRoundingModeSettings'
                            float_control_props->separateRoundingModeSettings);
                                               ^~
```

**Comment by jeremyk-lunarg** [comment]
Thank you for letting us know.

We have a known_good.json file containing tags and commit IDs for each repo required to build Vulkan-Tools that currently are known to work.

Right now we are using Vulkan-Headers 1.1.114.

I would suggest building with known_good.json for now.

If there are things in Vulkan-Headers 1.1.117 that you require for your development I would suggest keeping an eye on the repo for an update to known_good.json.

**Comment by dgkoch** [comment]
Fix in PR #235

**Comment by charles-lunarg** [comment]
Fixed with PR #240, closing this issue
