### PR TITLE
cubepp: Fix regression in VK_KHR_display

### LINKED ISSUE #631: vkcubepp (KHR_display) fails to build since v1.3.209
Regressed by c2f1a9494a90

```c++
$ cmake -DCUBE_WSI_SELECTION=DISPLAY -B /tmp/vulkan-tools_build
$ cmake --build /tmp/vulkan-tools_build
[...]
FAILED: cube/CMakeFiles/vkcubepp.dir/cube.cpp.o
/usr/bin/c++ -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_DISPLAY_KHR -I/tmp/vulkan-tools_build/cube -Icube -I/tmp/vulkan-tools_build/cube/.. -isystem /usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Werror -std=c++11 -fno-rtti -fvisibility=hidden -MD -MT cube/CMakeFiles/vkcubepp.dir/cube.cpp.o -MF cube/CMakeFiles/vkcubepp.dir/cube.cpp.o.d -o cube/CMakeFiles/vkcubepp.dir/cube.cpp.o -c cube/cube.cpp
cube/cube.cpp:2923:13: error: use of undeclared identifier 'plane_props'
        if (plane_props[plane_index].currentDisplay && (plane_props[plane_index].currentDisplay != display)) {
            ^
cube/cube.cpp:2923:57: error: use of undeclared identifier 'plane_props'
        if (plane_props[plane_index].currentDisplay && (plane_props[plane_index].currentDisplay != display)) {
                                                        ^
cube/cube.cpp:2952:84: error: use of undeclared identifier 'mode_props'
    vk::DisplayPlaneCapabilitiesKHR planeCaps = gpu.getDisplayPlaneCapabilitiesKHR(mode_props.displayMode, plane_index);
                                                                                   ^
cube/cube.cpp:2952:108: error: use of undeclared identifier 'plane_index'
    vk::DisplayPlaneCapabilitiesKHR planeCaps = gpu.getDisplayPlaneCapabilitiesKHR(mode_props.displayMode, plane_index);
                                                                                                           ^
cube/cube.cpp:2969:27: error: use of undeclared identifier 'mode_props'
    image_extent.setWidth(mode_props.parameters.visibleRegion.width).setHeight(mode_props.parameters.visibleRegion.height);
                          ^
cube/cube.cpp:2969:80: error: use of undeclared identifier 'mode_props'
    image_extent.setWidth(mode_props.parameters.visibleRegion.width).setHeight(mode_props.parameters.visibleRegion.height);
                                                                               ^
cube/cube.cpp:2974:53: error: use of undeclared identifier 'plane_props'
                                .setPlaneStackIndex(plane_props[plane_index].currentStackIndex)
                                                    ^
cube/cube.cpp:2974:65: error: use of undeclared identifier 'plane_index'; did you mean 'frame_index'?
                                .setPlaneStackIndex(plane_props[plane_index].currentStackIndex)
                                                                ^~~~~~~~~~~
                                                                frame_index
cube/cube.cpp:363:14: note: 'frame_index' declared here
    uint32_t frame_index = 0;
             ^
cube/cube.cpp:2972:49: error: use of undeclared identifier 'mode_props'
                                .setDisplayMode(mode_props.displayMode)
                                                ^
cube/cube.cpp:2973:48: error: use of undeclared identifier 'plane_index'
                                .setPlaneIndex(plane_index)
                                               ^
10 errors generated.
```

### PR DESCRIPTION
**Pull request by charles-lunarg**
Fixes #631

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
I'll check the fix later this day & will report back 👍🏻
