### ISSUE TITLE
vkcubepp + Wayland fails with Clang due to -Werror

### ISSUE THREAD

**Issue by jbeich** [KhronosGroup/Vulkan-Tools#532]
Regressed by 0143cbebff88f + ac9393317a5c (CC @mstoeckl). From [error log](https://github.com/KhronosGroup/Vulkan-Tools/files/6654758/vulkan-tools-1.2.181.log):
```c++
$ export CC=clang12 CXX=clang++12
$ cmake -DCUBE_WSI_SELECTION=WAYLAND -G Ninja -B /tmp/vktools_build
$ cmake --build /tmp/vktools_build
FAILED: cube/CMakeFiles/vkcubepp.dir/cube.cpp.o
clang++12 -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WAYLAND_KHR -Icube -Icube -Icube/.. -isystem /usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Werror -std=c++11 -fno-rtti -fvisibility=hidden -MD -MT cube/CMakeFiles/vkcubepp.dir/cube.cpp.o -MF cube/CMakeFiles/vkcubepp.dir/cube.cpp.o.d -o cube/CMakeFiles/vkcubepp.dir/cube.cpp.o -c cube/cube.cpp
cube/cube.cpp:416:40: error: unused variable 'shell_surface_listener' [-Werror,-Wunused-const-variable]
static const wl_shell_surface_listener shell_surface_listener = {handle_ping, handle_configure, handle_popup_done};
                                       ^
1 error generated.
```

**Comment by Tony-LunarG** [comment]
Fixed in #538

**Comment by jbeich** [comment]
I can still reproduce:
```c++
cube/cube.cpp:408:13: error: unused function 'handle_ping' [-Werror,-Wunused-function]
static void handle_ping(void *data, wl_shell_surface *shell_surface, uint32_t serial) {
            ^
cube/cube.cpp:412:13: error: unused function 'handle_configure' [-Werror,-Wunused-function]
static void handle_configure(void *data, wl_shell_surface *shell_surface, uint32_t edges, int32_t width, int32_t height) {}
            ^
cube/cube.cpp:414:13: error: unused function 'handle_popup_done' [-Werror,-Wunused-function]
static void handle_popup_done(void *data, wl_shell_surface *shell_surface) {}
            ^
3 errors generated.
```
