### ISSUE TITLE
vkcube + Display fails with Clang due to -Werror

### ISSUE THREAD

**Issue by jbeich** [KhronosGroup/Vulkan-Tools#531]
Regressed by 0143cbebff88f. From [error log](https://github.com/KhronosGroup/Vulkan-Tools/files/6654535/vulkan-tools-1.2.181.log):
```c
$ export CC=clang12 CXX=clang++12
$ cmake -DCUBE_WSI_SELECTION=DISPLAY -G Ninja -B /tmp/vktools_build
$ cmake --build /tmp/vktools_build
FAILED: cube/CMakeFiles/vkcube.dir/cube.c.o
clang12 -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_DISPLAY_KHR -Icube -Icube -Icube/.. -isystem /usr/local/include -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Werror -fvisibility=hidden -MD -MT cube/CMakeFiles/vkcube.dir/cube.c.o -MF cube/CMakeFiles/vkcube.dir/cube.c.o.d -o cube/CMakeFiles/vkcube.dir/cube.c.o -c cube/cube.c
cube/cube.c:3030:45: error: implicit conversion from enumeration type 'enum VkDisplayPlaneAlphaFlagBitsKHR' to different enumeration type 'VkCompositeAlphaFlagBitsKHR' (aka 'enum VkCompositeAlphaFlagBitsKHR') [-Werror,-Wenum-conversion]
    VkCompositeAlphaFlagBitsKHR alphaMode = VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR;
                                ~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cube/cube.c:3035:9: error: implicit conversion from enumeration type 'enum VkDisplayPlaneAlphaFlagBitsKHR' to different enumeration type 'VkCompositeAlphaFlagBitsKHR' (aka 'enum VkCompositeAlphaFlagBitsKHR') [-Werror,-Wenum-conversion]
        VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cube/cube.c:3034:9: error: implicit conversion from enumeration type 'enum VkDisplayPlaneAlphaFlagBitsKHR' to different enumeration type 'VkCompositeAlphaFlagBitsKHR' (aka 'enum VkCompositeAlphaFlagBitsKHR') [-Werror,-Wenum-conversion]
        VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cube/cube.c:3033:9: error: implicit conversion from enumeration type 'enum VkDisplayPlaneAlphaFlagBitsKHR' to different enumeration type 'VkCompositeAlphaFlagBitsKHR' (aka 'enum VkCompositeAlphaFlagBitsKHR') [-Werror,-Wenum-conversion]
        VK_DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cube/cube.c:3032:9: error: implicit conversion from enumeration type 'enum VkDisplayPlaneAlphaFlagBitsKHR' to different enumeration type 'VkCompositeAlphaFlagBitsKHR' (aka 'enum VkCompositeAlphaFlagBitsKHR') [-Werror,-Wenum-conversion]
        VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cube/cube.c:3053:29: error: implicit conversion from enumeration type 'VkCompositeAlphaFlagBitsKHR' (aka 'enum VkCompositeAlphaFlagBitsKHR') to different enumeration type 'VkDisplayPlaneAlphaFlagBitsKHR' (aka 'enum VkDisplayPlaneAlphaFlagBitsKHR') [-Werror,-Wenum-conversion]
    create_info.alphaMode = alphaMode;
                          ~ ^~~~~~~~~
6 errors generated.
```

**Comment by Tony-LunarG** [comment]
Fixed with #536
